config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  get 'home/index'

  resources :users, only: [:create]
  resources :user_sessions, only: [:create]

  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'user_sessions#new'
  get '/sign_out', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET user_sessions/new
  def new
  end

  # POST user_sessions
  def create(email:, password:)
    @user = login(email, password)

    if @user
      redirect_back_or_to(root_path)
    else
      flash.now[:alert] = "サインインに失敗しました。再度お試しください"
      render :new
    end
  end

  # GET user_sessions/destroy
  def destroy
    logout
    redirect_to root_path, notice: 'サインアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET user/new
  def new
    # ログイン済みならユーザ作成画面にはアクセスできない
    if logged_in?
      redirect_to root_path
    end

    @user = User.new
  end

  # POST user
  def create(user)
    @user = User.new(user.permit(:email, :password, :password_confirmation))

    if @user.save
      redirect_to root_path, notice: 'ユーザー登録に成功しました'
    else
      flash.now[:alert] = "ユーザー登録に失敗しました。再度お試しください"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div id="nav" style="margin-top:30px;">
      <% if logged_in? %>
        <strong><%= current_user.email %></strong> としてログイン中です |
        <%= link_to "サインアウト", sign_out_url, method: :get %>
      <% else %>
        <%= link_to "サインアップ", sign_up_url %> |
        <%= link_to "サインイン", sign_in_url %>
      <% end %>
    </div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>

    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<h1>サインイン</h1>
<h2>UserSessions#new</h2>
<p>Find me in app/views/user_sessions/new.html.erb</p>

<%= form_with url: user_sessions_path, method: :post do |form| %>

  <div class="field">
    <%= form.label :email, :メールアドレス %><br />
    <%= form.text_field :email  %>
  </div>

  <div class="field">
    <%= form.label :password, :パスワード %><br />
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit :サインイン %>
  </div>

<% end %>

<%= link_to "戻る", root_path %>

app/views/users/new.html.erb
<h1>サインアップ</h1>
<h2>Users#new</h2>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_with model: @user, url: users_path, method: :post do |form| %>

  <div class="field">
    <%= form.label :email, :メールアドレス %><br />
    <%= form.text_field :email  %>
  </div>

  <div class="field">
    <%= form.label :password, :パスワード %><br />
    <%= form.password_field :password  %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, :パスワードを再度入力してください %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit :登録 %>
  </div>
<% end %>

<%= link_to "戻る", root_path %>